"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-04-30 02:32:40.047420+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_categories',
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('states',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('iecc_zone', sa.String(length=8), nullable=False),
    sa.Column('building_code', sa.String(length=64), nullable=False),
    sa.Column('hurricane', sa.Integer(), nullable=False),
    sa.Column('tornado', sa.Integer(), nullable=False),
    sa.Column('flood', sa.Integer(), nullable=False),
    sa.Column('winter', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Integer(), nullable=False),
    sa.Column('seismic', sa.Integer(), nullable=False),
    sa.Column('wildfire', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_states_full_name'), ['full_name'], unique=True)

    op.create_table('construction_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hazard_key', sa.String(length=16), nullable=False),
    sa.Column('tip', sa.String(length=256), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hazard_key'], ['risk_categories.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('construction_tips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_construction_tips_hazard_key'), ['hazard_key'], unique=False)

    op.create_table('decadal_trends',
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('decade', sa.String(length=8), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_code', 'decade')
    )
    op.create_table('historical_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('wiki', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_events_state_code'), ['state_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_events_state_code'))

    op.drop_table('historical_events')
    op.drop_table('decadal_trends')
    with op.batch_alter_table('construction_tips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_construction_tips_hazard_key'))

    op.drop_table('construction_tips')
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_states_full_name'))

    op.drop_table('states')
    op.drop_table('risk_categories')
    # ### end Alembic commands ###
