"""add nri counties table

Revision ID: 0003_add_nri_counties_table
Revises: 0002_add_analyses_table
Create Date: 2026-05-01 20:34:51.979982+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_add_nri_counties_table'
down_revision: Union[str, None] = '0002_add_analyses_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nri_counties',
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('nws_zone_id', sa.String(length=8), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('county_name', sa.String(length=64), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_rating', sa.String(length=32), nullable=True),
    sa.Column('hurricane', sa.Float(), nullable=False),
    sa.Column('tornado', sa.Float(), nullable=False),
    sa.Column('flood', sa.Float(), nullable=False),
    sa.Column('winter', sa.Float(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=False),
    sa.Column('seismic', sa.Float(), nullable=False),
    sa.Column('wildfire', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('county_fips')
    )
    with op.batch_alter_table('nri_counties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nri_counties_nws_zone_id'), ['nws_zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nri_counties_state_code'), ['state_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nri_counties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nri_counties_state_code'))
        batch_op.drop_index(batch_op.f('ix_nri_counties_nws_zone_id'))

    op.drop_table('nri_counties')
    # ### end Alembic commands ###
